services:
  - type: web
    name: eazyride-haye-admin
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://eazyride-haye-db.onrender.com
